### ISSUE TITLE
Include Verilator version requirements (or a reference to the version requirement in the chisel-test repo). 

### ISSUE THREAD

**Issue by HakamAtassi** [chipsalliance/chisel-template#125]
Had issues with ```sbt test``` causing the build process to crash due to errors vaguely indicative of a verilator issue. Eventually referenced https://github.com/ucb-bar/chiseltest which suggested using verilator 4.202 which fixed my issues on Ubuntu 22.04.

**Comment by seldridge** [comment]
This may be a duplicate of #128. Can you try again with `main` and see if everything is good?

**Comment by HakamAtassi** [comment]
It works!

**Comment by seldridge** [comment]
👍 Glad to hear it. Thanks for the report, update, and closing the issue.
